language: node_js
node_js: "8"
cache:
  yarn: true

before_install:
  - cd website # changes directory for all subsequent steps

install:
  - yarn install --frozen-lockfile

script:
  - yarn build:develop
  