services:
  # This configuration is for the production version of docs (docs.meshcloud.io)
  - type: web
    name: meshcloud-docs
    env: static
    branch: master
    # Production requires a different build command
    rootDir: website
    buildCommand: yarn build:master
    staticPublishPath: build/meshcloud-docs
    pullRequestPreviewsEnabled: false
    buildFilter:
      # For the master build we just want to always do a build, no matter what files were changed.
      paths:
        - **/*
    routes:
      # These rewrites prevent Plausible from being blocked by ad-blockers.
      - type: rewrite
        source: /js/script.js
        destination: https://plausible.io/js/plausible.js
      - type: rewrite
        source: /api/event
        destination: https://plausible.io/api/event
      # This rewrite will serve our internal API documentation neatly under `docs.meshcloud.io/api/*`
      - type: rewrite
        source: /api/*
        destination: http://docs.meshcloud.io.s3-website.eu-central-1.amazonaws.com/api/*
  # This configuration is for the development version of docs (docs.dev.meshcloud.io) and also makes sure PRs are opened
  # against the develop branch.
  - type: web
    name: meshcloud-docs-dev
    env: static
    # The default branch of meshcloud-docs is the develop branch
    rootDir: website
    buildCommand: yarn build:develop
    staticPublishPath: build/meshcloud-docs
    pullRequestPreviewsEnabled: true
    buildFilter:
      # Only changes in docs or website folder should actually lead to a build.
      # And we check render.yaml, so we can directly apply any hosting configuration.
      paths:
        - docs/*
        - website/*
        - render.yaml
    routes:
      # These rewrites prevent Plausible from being blocked by ad-blockers.
      - type: rewrite
        source: /js/script.js
        destination: https://plausible.io/js/plausible.js
      - type: rewrite
        source: /api/event
        destination: https://plausible.io/api/event
      # This rewrites will serve our internal API documentation neatly under `docs.meshcloud.io/api/*`
      - type: rewrite
        source: /api/*
        destination: http://docs.dev.meshcloud.io.s3-website.eu-central-1.amazonaws.com/api/*