const fs = require('fs');
const path = require('path');

/**
 * This script modifies the Docusaurus sidebar configuration that is generated by the OpenAPI plugin.
 */

/**
 * Removes introduction page from a sidebar file
 */
function removeIntroduction(relativePath, introId) {
    const fullPath = path.join(__dirname, relativePath);
    const sidebar = require(fullPath).default;
    const filtered = sidebar.filter((item) => item.id !== introId);
    fs.writeFileSync(fullPath, `module.exports = ${JSON.stringify(filtered, null, 2)};\n`);
    return filtered;
}

// Process main API sidebar
let filteredSidebar = removeIntroduction('../docs/api/sidebar.ts', 'api/meshstack-api-documentation');

// Add all meshObjects page to the meshObject Import.
// We documented this by hand and this API is anyway planned to be deprecated.
const meshObjectImportItem = filteredSidebar.find(item => item.label === 'meshObject Import');
meshObjectImportItem.items.push('api/all-meshobjects');

// Group entries that have anything to do with meshObject API (name contains "object")
const objectItems = filteredSidebar.filter(
    item => typeof item.label === 'string' && item.label.toLowerCase().includes('object')
);

filteredSidebar = filteredSidebar.filter(
    item => !(typeof item.label === 'string' && item.label.toLowerCase().includes('object'))
);

if (objectItems.length > 0) {
    filteredSidebar.push({
        type: 'category',
        label: 'meshObject API',
        items: objectItems,
    });
}

fs.writeFileSync(
    path.join(__dirname, '../docs/api/sidebar.ts'),
    `module.exports = ${JSON.stringify(filteredSidebar, null, 2)};\n`
);

console.log('✅ Main API sidebar updated: Introduction removed, object entries grouped!');

// Process metering-api sidebar
removeIntroduction('../docs/metering-api/sidebar.ts', 'metering-api/meshmetering-api-documentation');

console.log('✅ Metering API sidebar updated: Introduction removed!');
