const fs = require('fs');
const path = require('path');

/**
 * This script modifies the Docusaurus sidebar configuration that is generated by the OpenAPI plugin.
 */
const sidebarPath = path.join(__dirname, '../docs/api/sidebar.ts');
const sidebarArray = require(sidebarPath).default; // or .ts if compiled

const introductionId = 'api/meshstack-api-documentation';
// Remove Introduction
let filteredSidebar = sidebarArray.filter((item) => item.id !== introductionId);

// Add all meshObjects page to the meshObject Import.
// We documented this by hand and this API is anyway planned to be deprecated.
const meshObjectImportItem = filteredSidebar.find(item => item.label === 'meshObject Import');
meshObjectImportItem.items.push('api/all-meshobjects');

// Group entries that have anything to do with meshObject API (name contains "object")
const objectItems = filteredSidebar.filter(
    item => typeof item.label === 'string' && item.label.toLowerCase().includes('object')
);

filteredSidebar = filteredSidebar.filter(
    item => !(typeof item.label === 'string' && item.label.toLowerCase().includes('object'))
);

if (objectItems.length > 0) {
    filteredSidebar.push({
        type: 'category',
        label: 'meshObject API',
        items: objectItems,
    });
}

const newContent = `module.exports = ${JSON.stringify(filteredSidebar, null, 2)};\n`;

fs.writeFileSync(sidebarPath, newContent);

console.log('✅ Sidebar updated: Introduction removed, object entries grouped!');
